### ISSUE TITLE
osgi service check in cosbench-start.sh not working

### ISSUE THREAD

**Issue by dblacknc** [sine-io/cosbench-sineio#1]
OS is Ubuntu 20.10, with netcat-openbsd 1.217-2ubuntu1.  cosbench-ehualu 0.4.7.5 from the .tar.gz binaries in the tree.

The loop in cosbench-start.sh that checks for module active fails because the osgi service listener seems to need a leading CR to accept the ss command.   There's also some cruft in the boot log displayed at the end, so I filtered that a bit.  Proposed patch:

```
83c83
<                 echo -e "ss -s ACTIVE cosbench\ndisconnect\n" | $TOOL $TOOL_PARAMS 0.0.0.0 $OSGI_CONSOLE_PORT | grep $module >> /dev/null
---
>                 echo -e "\nss -s ACTIVE cosbench\ndisconnect\n" | $TOOL $TOOL_PARAMS 0.0.0.0 $OSGI_CONSOLE_PORT | grep $module >> /dev/null
114c114
< cat $BOOT_LOG
---
> cat $BOOT_LOG | fgrep -v '<>'

```

**Comment by kisscelia** [comment]
Hi, @dblacknc 
Any errors when booting drivers and controller?

I try to start cosbench drivers on Centos 7.9, It's OK.
![image](https://user-images.githubusercontent.com/13063673/147041916-94cf571c-7c99-4e3a-9429-610323fdd09b.png)

I will try it on Ubuntu later, thanks.

**Comment by dblacknc** [comment]
Yes, it does work normally on CentOS.  This error is specific to Ubuntu - and I believe it's related to the build of netcat Ubuntu uses.  This is a known issue in COSbench.  Different people have found different workaround.  After much experimentation I found it to be most simply fixed with the extra \n before the "ss" command, and shouldn't break CentOS.

**Comment by kisscelia** [comment]
OK, I will try it on Ubuntu & Centos, and will close this issue  if both ok.

**Comment by kisscelia** [comment]
20.10 is not a LTS version.

I will try it in LTS version(22.04)

change nc to telnet.

**Comment by kisscelia** [comment]
passed

dockerfile:
![image](https://user-images.githubusercontent.com/13063673/196143480-3a78963b-0157-4ea9-9e3a-cf706462763e.png)

docker-compose:
```
version: '3.9'

services:
  driver1:
    image: "sineio/cosbench-sineio:0.4.7.9-ubuntu"
    environment:
      CONTROLLER: false
      DRIVER: true
      DRIVER_PORT: 18088
      COSBENCH_PLUGINS: "SIO,S3"
    volumes:
      - /data/cosbench/driver1-log/:/cosbench/log
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:18088/driver"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"

  driver2:
    image: "sineio/cosbench-sineio:0.4.7.9-ubuntu"
    environment:
      CONTROLLER: false
      DRIVER: true
      DRIVER_PORT: 18188
      COSBENCH_PLUGINS: "SIO,S3"
    volumes:
      - /data/cosbench/driver2-log/:/cosbench/log
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:18188/driver"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"

  driver3:
    image: "sineio/cosbench-sineio:0.4.7.9-ubuntu"
    environment:
      CONTROLLER: false
      DRIVER: true
      DRIVER_PORT: 18288
      COSBENCH_PLUGINS: "SIO,S3"
    volumes:
      - /data/cosbench/driver3-log/:/cosbench/log
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:18288/driver"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"

  controller:
    image: "sineio/cosbench-sineio:0.4.7.9-ubuntu"
    environment:
      CONTROLLER: true
      DRIVER: false
      DRIVERS: "http://127.0.0.1:18088/driver,http://127.0.0.1:18188/driver,http://127.0.0.1:18288/driver,"
    depends_on:
      driver1:
        condition: service_healthy
      driver2:
        condition: service_healthy
      driver3:
        condition: service_healthy
    volumes:
      - /data/cosbench/archive/:/cosbench/archive
      - /data/cosbench/controller-log/:/cosbench/log
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:19088/controller/index.html"]
      interval: 60s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"
```
start log:
![image](https://user-images.githubusercontent.com/13063673/196143855-49fa841e-e05f-4721-8652-662ec4b4e870.png)
