### ISSUE TITLE
when start with docker-compose cause error

### ISSUE THREAD

**Issue by T-TRz879** [sine-io/cosbench-sineio#40]
<img width="611" alt="image" src="https://github.com/sine-io/cosbench-sineio/assets/50860504/46dc5d4a-2126-4bac-b6f0-517e83ef5d93">
<img width="1326" alt="image" src="https://github.com/sine-io/cosbench-sineio/assets/50860504/7246dc1e-15c0-434e-8731-b8d95aee6cc7">

docker image
<img width="718" alt="image" src="https://github.com/sine-io/cosbench-sineio/assets/50860504/25da9788-dc09-4295-b6fb-49332cbe0e8a">

docker-compose.yml
```
version: '3.9'

services:
  driver1:
    image: "sineio/cosbench-sineio:0.4.7.9-ubuntu-local"
    environment:
      CONTROLLER: false
      DRIVER: true
      DRIVER_PORT: 18088
      COSBENCH_PLUGINS: "S3"
    volumes:
      - ./data/cosbench/driver1-log/:/cosbench/log
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:18088/driver"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"

  driver2:
    image: "sineio/cosbench-sineio:0.4.7.9-ubuntu-local"
    environment:
      CONTROLLER: false
      DRIVER: true
      DRIVER_PORT: 18188
      COSBENCH_PLUGINS: "S3"
    volumes:
      - ./data/cosbench/driver2-log/:/cosbench/log
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:18188/driver"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"

  driver3:
    image: "sineio/cosbench-sineio:0.4.7.9-ubuntu-local"
    environment:
      CONTROLLER: false
      DRIVER: true
      DRIVER_PORT: 18288
      COSBENCH_PLUGINS: "S3"
    volumes:
      - ./data/cosbench/driver3-log/:/cosbench/log
      - /etc/resolv.conf:/etc/resolv.conf:ro
      - /etc/hosts:/etc/hosts:ro
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:18288/driver"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"

  controller:
    image: "sineio/cosbench-sineio:0.4.7.9-ubuntu-local"
    environment:
      CONTROLLER: true
      DRIVER: false
      DRIVERS: "http://127.0.0.1:18088/driver,http://127.0.0.1:18188/driver,http://127.0.0.1:18288/driver,"
    depends_on:
      driver1:
        condition: service_healthy
      driver2:
        condition: service_healthy
      driver3:
        condition: service_healthy
    volumes:
      - ./data/cosbench/archive/:/cosbench/archive
      - ./data/cosbench/controller-log/:/cosbench/log
      - /etc/resolv.conf:/etc/resolv.conf
      - /etc/hosts:/etc/hosts
      - /etc/localtime:/etc/localtime:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:19088/controller/index.html"]
      interval: 60s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    tty: true
    stdin_open: true
    network_mode: "host"
```

Dockerfile
```
FROM ubuntu:22.04
MAINTAINER "sine.wang" <sinecelia.wang@gmail.com>

ARG VERSION=0.4.7.9
ENV COS_VERSION=${VERSION}
ENV COS_PREFIX="cosbench-"
ENV COS_SUFFIX="-sineio"
ENV COS_FILENAMEEXT=".tar.gz"

WORKDIR /

# cosbench-0.4.7.9-sineio.tar.gz
ADD ${COS_PREFIX}${COS_VERSION}${COS_SUFFIX}${COS_FILENAMEEXT} .

RUN mv /${COS_PREFIX}${COS_VERSION}${COS_SUFFIX} /cosbench \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y \
         dpkg apt-transport-https curl apt-utils telnet netcat net-tools openjdk-8-jre \
    && rm -f /bin/sh && ln -s /bin/bash /bin/sh


WORKDIR /cosbench

COPY start-cosbench.sh .

CMD ["sh", "/cosbench/start-cosbench.sh"]
```
